name: sportmatch

services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sportmatch
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d sportmatch"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pgdata:
