name: Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  verificar:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
